### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GOUKI9999** [hasscc/catlink#29]
2024.8.1 core ,HACS updated the intergration to lastest version
some error in log
Error during setup of component catlink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/catlink/modules/devices_coordinator.py", line 57, in _async_update_data
    dvc = ScooperDevice(dat, self, additional_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/catlink/modules/scooper_device.py", line 37, in __init__
    self.empty_litter_box_weight = self.additional_config.empty_weight or 0.0
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'empty_weight'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/catlink/__init__.py", line 38, in async_setup
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 288, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: 'NoneType' object has no attribute 'empty_weight'

and

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/catlink/modules/devices_coordinator.py", line 57, in _async_update_data
    dvc = ScooperDevice(dat, self, additional_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/catlink/modules/scooper_device.py", line 37, in __init__
    self.empty_litter_box_weight = self.additional_config.empty_weight or 0.0
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'empty_weight'

**Comment by GOUKI9999** [comment]
I have to rollback to d2c73545c81616b327e60cf5a98b968de9e0dfe7   ,28/aug version to keep it works guys , maybe it need a fix :)
